In [0]:
!pip install sklearn


In [0]:
#Loading the Library with the Iris data
from sklearn.datasets import load_iris

#Load scikit random forest classifier Library
from sklearn.ensemble import RandomForestClassifier

import pandas as pd
import numpy as np

#Setting Random seed
np.random.seed(0)

In [21]:
#create an object and name it iris(whatever u want) and load the iris data with load_iris function

iris = load_iris()

#create a data frame with four features
df = pd.DataFrame(iris.data , columns = iris.feature_names)

df.head(10)

#The question is where from the data come To check the array of data use:
#print(iris)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [26]:
#So now we add a new colum for the species name
#When we want to add a new colum we can just it by write colom name into the datasets as like df['spceis']

df['species'] = pd.Categorical.from_codes(iris.target , iris.target_names)
df.head(10)

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  species
0                5.1               3.5  ...               0.2   setosa
1                4.9               3.0  ...               0.2   setosa
2                4.7               3.2  ...               0.2   setosa
3                4.6               3.1  ...               0.2   setosa
4                5.0               3.6  ...               0.2   setosa
5                5.4               3.9  ...               0.4   setosa
6                4.6               3.4  ...               0.3   setosa
7                5.0               3.4  ...               0.2   setosa
8                4.4               2.9  ...               0.2   setosa
9                4.9               3.1  ...               0.1   setosa

[10 rows x 5 columns]

In [29]:
#Creating Test and Train Data

df['is_train'] = np.random.uniform(0 , 1, len(df)) <= .75 #Less then 75% is true and rest of the false(randomly )

df.head(10)

sepal length (cm)  sepal width (cm)  ...  species  is_train
0                5.1               3.5  ...   setosa      True
1                4.9               3.0  ...   setosa     False
2                4.7               3.2  ...   setosa      True
3                4.6               3.1  ...   setosa      True
4                5.0               3.6  ...   setosa      True
5                5.4               3.9  ...   setosa     False
6                4.6               3.4  ...   setosa     False
7                5.0               3.4  ...   setosa      True
8                4.4               2.9  ...   setosa      True
9                4.9               3.1  ...   setosa      True

[10 rows x 6 columns]

In [34]:
#Create dataframe with test rows and training rows 

train , test = df[df['is_train']==True] , df[df['is_train']==False]

print('Observation in train data :' ,len(train))
print('Observation in test data :' , len(test))


Observation in train data : 112
Observation in test data : 38


In [37]:
#Readable to Humans
#Creates a list of the features columns names

features = df.columns[:4]
#view features
(features) 

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [41]:
#converting each species name into digits

y = pd.factorize(train['species'])[0]

#viwe target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [45]:
#Creating a Random Forest Classifier
clf = RandomForestClassifier(n_jobs = 2 , random_state = 0)

#training the classifier
clf.fit(train[features] , y)


/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [46]:
#Apply the trained classifier to the test 

clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [49]:
#view the predicted probabilities of the first 10 observation 
clf.predict_proba(test[features]) [0:10] #[10:20]

array([[1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0.9, 0.1, 0. ],
       [0.9, 0.1, 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ]])

In [52]:
#mapping names for the plants for each predicted plant class

preds = iris.target_names[clf.predict(test[features])]

#view the PREDICTED species for the first five observation

preds[10:50]

array(['versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'versicolor',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica'],
      dtype='<U10')

In [53]:
#view the Actual Species for the first five observations 
test['species'].head()

1     setosa
5     setosa
6     setosa
13    setosa
14    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [55]:
#Creating Confusion Matrix 

pd.crosstab(test['species'] , preds , rownames = ['Actual Species'] , colnames = ['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 10           0          0
versicolor              0           9          0
virginica               0           1         18